import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";

import { Button } from "@mantine/core";

export const getServerSideProps = async () => {
  const res = await fetch(`https://api.kanye.rest`);
  const quote = await res.json();

  return {
    props: {
      quote,
    },
  };
};

export default function Home({ quote }) {
  const [stateQuote, setQuote] = useState("");

  const getNewData = async () => {
    const res = await fetch(`https://api.kanye.rest`);
    setQuote(await res.json());
  };

  console.log(stateQuote);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{quote.quote}</h1>
        <Button
          variant="gradient"
          gradient={{ from: "indigo", to: "cyan" }}
          size="lg"
          className={styles.button}
          onClick={() => {
            window.location.reload();
          }}
        >
          New Quote
        </Button>
      </main>
    </div>
  );
}
