import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export const getStaticProps = async () => {
  const res = await fetch(`https://api.kanye.rest`);
  const quote = await res.json();

  return {
    props: {
      quote,
    },
  };
};

export default function Home({ quote }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{quote.quote}</h1>
      </main>
    </div>
  );
}
